# Generated by Django 5.1.4 on 2026-09-14 09:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('blog', '0005_blogpost_excerpt'),
    ]

    operations = [
        migrations.CreateModel(
            name='Faq',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=300)),
                ('answer', models.TextField(help_text='Plain text or simple HTML (e.g. links) is fine.')),
                ('position', models.PositiveSmallIntegerField(default=0, help_text='Lower = appears first.')),
                ('is_active', models.BooleanField(default=True, help_text='Inactive entries are hidden from the live site without deleting them.')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('source_post', models.ForeignKey(blank=True, help_text='The blog post this FAQ was gathered from, if any.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='faq_entries', to='blog.blogpost')),
            ],
            options={
                'verbose_name': 'FAQ',
                'verbose_name_plural': 'FAQs',
                'ordering': ['position', 'id'],
            },
        ),
    ]
