# Generated by Django 5.1.4 on 2026-09-15 08:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formbuilder', '0005_formdefinition_webhook_enabled_and_more'),
        ('leads', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='inquiry',
            name='form',
            field=models.ForeignKey(blank=True, help_text='Which CMS-managed form this inquiry was submitted through, if any.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inquiries', to='formbuilder.formdefinition'),
        ),
    ]
