# Generated by Django 5.1.4 on 2026-09-14 03:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ApplicationCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(max_length=60, unique=True)),
                ('label', models.CharField(max_length=80)),
                ('description', models.CharField(blank=True, max_length=500)),
                ('accent', models.CharField(blank=True, help_text='Hex accent colour, e.g. #85addc', max_length=7)),
                ('image', models.CharField(blank=True, max_length=500)),
                ('position', models.PositiveIntegerField(default=0)),
                ('enabled', models.BooleanField(default=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Application Categories',
                'ordering': ['position', 'id'],
            },
        ),
        migrations.CreateModel(
            name='ApplicationProject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(max_length=100, unique=True)),
                ('label', models.CharField(max_length=150)),
                ('finish', models.CharField(blank=True, max_length=150)),
                ('image', models.CharField(blank=True, help_text='Hero / cover image.', max_length=500)),
                ('tall', models.BooleanField(default=False, help_text='Layout hint for the masonry grid.')),
                ('description', models.TextField(blank=True)),
                ('location', models.CharField(blank=True, max_length=150)),
                ('year', models.CharField(blank=True, max_length=10)),
                ('designer', models.CharField(blank=True, max_length=150)),
                ('area', models.CharField(blank=True, max_length=100)),
                ('gallery', models.JSONField(blank=True, default=list)),
                ('highlights', models.JSONField(blank=True, default=list)),
                ('products', models.JSONField(blank=True, default=list)),
                ('position', models.PositiveIntegerField(default=0)),
                ('enabled', models.BooleanField(default=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='projects', to='applications.applicationcategory')),
            ],
            options={
                'ordering': ['position', 'id'],
            },
        ),
    ]
