# Generated by Django 5.1.4 on 2026-09-14 03:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0002_seed_applications'),
    ]

    operations = [
        migrations.AddField(
            model_name='applicationcategory',
            name='gallery',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AlterField(
            model_name='applicationcategory',
            name='image',
            field=models.CharField(blank=True, help_text='Hero image for the category banner.', max_length=500),
        ),
    ]
