# Generated by Django 5.1.4 on 2026-09-14 04:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GalleryCatalogue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(max_length=60, unique=True)),
                ('label', models.CharField(max_length=80)),
                ('cover_image', models.CharField(blank=True, help_text='Card thumbnail on /applications.', max_length=500)),
                ('position', models.PositiveIntegerField(default=0)),
                ('enabled', models.BooleanField(default=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['position', 'id'],
            },
        ),
        migrations.CreateModel(
            name='GalleryImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.CharField(max_length=500)),
                ('product_id', models.CharField(blank=True, help_text='Laminate code shown to visitors, e.g. "6005-5". Leave blank to auto-number.', max_length=40)),
                ('position', models.PositiveIntegerField(default=0)),
                ('enabled', models.BooleanField(default=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('catalogue', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='gallery.gallerycatalogue')),
            ],
            options={
                'ordering': ['position', 'id'],
            },
        ),
    ]
