# Generated by Django 5.1.4 on 2026-05-30 02:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0001_initial'),
        ('media_library', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PageTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('product_type_label', models.CharField(help_text='e.g. "High Pressure Laminates"', max_length=100)),
                ('url_pattern', models.CharField(default='{product}-in-{city}', help_text='e.g. {product}-in-{city} — will be slugified', max_length=100)),
                ('default_h1', models.CharField(blank=True, max_length=255)),
                ('default_hero_heading', models.CharField(blank=True, max_length=255)),
                ('default_hero_desc', models.TextField(blank=True)),
                ('default_main_content', models.TextField(blank=True)),
                ('why_choose_us', models.JSONField(blank=True, default=list)),
                ('faqs', models.JSONField(blank=True, default=list)),
                ('default_schema_type', models.CharField(choices=[('LocalBusiness', 'Local Business'), ('Product', 'Product'), ('FAQPage', 'FAQ Page'), ('Organization', 'Organization'), ('Article', 'Article'), ('BreadcrumbList', 'Breadcrumb List')], default='LocalBusiness', max_length=20)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('gallery', models.ManyToManyField(blank=True, related_name='page_templates', to='media_library.mediaasset')),
                ('related_products', models.ManyToManyField(blank=True, related_name='page_templates', to='catalog.product')),
            ],
        ),
        migrations.CreateModel(
            name='CityPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(max_length=100)),
                ('state', models.CharField(blank=True, max_length=100)),
                ('slug', models.SlugField(blank=True, max_length=200, unique=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('published', 'Published')], default='draft', max_length=10)),
                ('h1_title', models.CharField(blank=True, max_length=255, null=True)),
                ('hero_heading', models.CharField(blank=True, max_length=255, null=True)),
                ('hero_description', models.TextField(blank=True, null=True)),
                ('main_content', models.TextField(blank=True, null=True)),
                ('why_choose_us', models.JSONField(blank=True, null=True)),
                ('faqs', models.JSONField(blank=True, null=True)),
                ('testimonials', models.JSONField(blank=True, default=list)),
                ('seo_title', models.CharField(blank=True, max_length=255)),
                ('meta_description', models.TextField(blank=True, max_length=320)),
                ('meta_keywords', models.CharField(blank=True, max_length=500)),
                ('canonical_url', models.URLField(blank=True)),
                ('og_title', models.CharField(blank=True, max_length=255)),
                ('og_description', models.TextField(blank=True, max_length=320)),
                ('twitter_title', models.CharField(blank=True, max_length=255)),
                ('twitter_description', models.TextField(blank=True, max_length=280)),
                ('schema_type', models.CharField(blank=True, choices=[('LocalBusiness', 'Local Business'), ('Product', 'Product'), ('FAQPage', 'FAQ Page'), ('Organization', 'Organization'), ('Article', 'Article'), ('BreadcrumbList', 'Breadcrumb List')], max_length=20)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('gallery', models.ManyToManyField(blank=True, related_name='city_pages', to='media_library.mediaasset')),
                ('og_image', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='city_page_og', to='media_library.mediaasset')),
                ('related_products', models.ManyToManyField(blank=True, related_name='city_pages', to='catalog.product')),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='city_pages', to='pages.pagetemplate')),
            ],
            options={
                'ordering': ['city'],
            },
        ),
    ]
