# Generated by Django 5.1.4 on 2026-09-13 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0004_alter_pagesection_block_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pagesection',
            name='block_type',
            field=models.CharField(choices=[('hero', 'Hero Slider'), ('about', 'About / Intro'), ('horizontal_showcase', 'Collections Showcase'), ('special_edition', 'Special Edition'), ('why_us', 'Why Us (carousel)'), ('applications', 'Applications Gallery'), ('rewards', 'Rewards App'), ('cta', 'Closing CTA Banner'), ('blog_teaser', 'Editorial / Blog Teaser'), ('rich_text', 'Rich Text'), ('image_text', 'Image + Text'), ('cta_banner', 'CTA Banner'), ('page_hero', 'Page Hero'), ('content_section', 'Content Section'), ('feature_cards', 'Feature Cards'), ('contact_details', 'Contact Details'), ('faq', 'FAQ'), ('testimonials', 'Testimonials'), ('gallery', 'Image Gallery'), ('team', 'Team'), ('pricing', 'Pricing Table'), ('stats', 'Stats Strip'), ('logos_strip', 'Logos Strip'), ('video_embed', 'Video')], max_length=40),
        ),
    ]
