# Generated by Django 5.1.4 on 2026-09-14 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0006_seed_more_pages'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitepage',
            name='is_published',
            field=models.BooleanField(default=True, help_text='Unpublished (draft) pages return 404 on the live site.'),
        ),
    ]
