# Generated by Django 5.1.4 on 2026-09-09 04:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='featured_image_url',
            field=models.URLField(blank=True, help_text='External banner / featured image URL. Used when no Media Library image is set.', max_length=500),
        ),
        migrations.AddField(
            model_name='blogpost',
            name='layout',
            field=models.CharField(choices=[('sidebar', 'Content + right sidebar'), ('full', 'Full width (no sidebar)')], default='sidebar', help_text='Public article layout. Sidebar shows author / categories / tags.', max_length=12),
        ),
    ]
