# Generated by Django 5.1.4 on 2026-09-09 05:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_blogpost_featured_image_url_blogpost_layout'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='show_author',
            field=models.BooleanField(default=True, help_text='Show the author card in the sidebar.'),
        ),
        migrations.AddField(
            model_name='blogpost',
            name='show_related',
            field=models.BooleanField(default=True, help_text="Show the 'Recommended articles' section at the end of the post."),
        ),
        migrations.AddField(
            model_name='blogpost',
            name='show_share',
            field=models.BooleanField(default=True, help_text='Show social share buttons (Facebook, WhatsApp, email…) in the sidebar.'),
        ),
    ]
