# Generated by Django 5.1.4 on 2026-09-13 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_blogpost_show_author_blogpost_show_related_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='faqs',
            field=models.JSONField(blank=True, default=list, help_text='Accordion FAQ entries shown at the end of the article: [{question, answer}].'),
        ),
    ]
