# Generated by Django 5.1.4 on 2026-09-14 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_blogpost_faqs'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='excerpt',
            field=models.CharField(blank=True, help_text='Short description shown on blog cards and previews (recommended 350-450 characters).', max_length=450),
        ),
    ]
