# Generated by Django 5.1.4 on 2026-09-08 03:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HomeSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('block_type', models.CharField(choices=[('hero', 'Hero Slider'), ('about', 'About / Intro'), ('horizontal_showcase', 'Collections Showcase'), ('special_edition', 'Special Edition'), ('why_us', 'Why Us (carousel)'), ('applications', 'Applications Gallery'), ('rewards', 'Rewards App'), ('cta', 'Closing CTA Banner'), ('blog_teaser', 'Editorial / Blog Teaser'), ('rich_text', 'Rich Text'), ('image_text', 'Image + Text'), ('cta_banner', 'CTA Banner')], max_length=40)),
                ('label', models.CharField(help_text='Internal name shown in the CMS list (not published).', max_length=120)),
                ('anchor_id', models.SlugField(blank=True, help_text='Optional id for the <section> tag (e.g. "about" → /#about).', max_length=60)),
                ('position', models.PositiveIntegerField(default=0)),
                ('enabled', models.BooleanField(default=True)),
                ('content', models.JSONField(blank=True, default=dict)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Home Section',
                'ordering': ['position', 'id'],
            },
        ),
    ]
