# Generated by Django 5.1.4 on 2026-09-09 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0002_seed_sections'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homesection',
            name='block_type',
            field=models.CharField(choices=[('hero', 'Hero Slider'), ('about', 'About / Intro'), ('horizontal_showcase', 'Collections Showcase'), ('special_edition', 'Special Edition'), ('why_us', 'Why Us (carousel)'), ('applications', 'Applications Gallery'), ('rewards', 'Rewards App'), ('cta', 'Closing CTA Banner'), ('blog_teaser', 'Editorial / Blog Teaser'), ('rich_text', 'Rich Text'), ('image_text', 'Image + Text'), ('cta_banner', 'CTA Banner'), ('page_hero', 'Page Hero'), ('content_section', 'Content Section'), ('feature_cards', 'Feature Cards'), ('contact_details', 'Contact Details'), ('faq', 'FAQ')], max_length=40),
        ),
    ]
