# Generated by Django 5.1.4 on 2026-09-13 18:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FormDefinition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(help_text='Referenced by pages/blocks, e.g. "quote-request".', max_length=80, unique=True)),
                ('name', models.CharField(max_length=120)),
                ('description', models.CharField(blank=True, max_length=255)),
                ('submit_label', models.CharField(default='Submit', max_length=60)),
                ('success_message', models.CharField(default="Thank you! We'll be in touch shortly.", max_length=255)),
                ('notify_emails', models.CharField(blank=True, help_text="Comma-separated emails notified on submission. Falls back to the site's default notify list.", max_length=500)),
                ('is_system', models.BooleanField(default=False, help_text='System forms cannot be deleted from the CMS.')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Form',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='FormSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.JSONField(blank=True, default=dict)),
                ('source_page', models.CharField(blank=True, max_length=500)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('form', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to='formbuilder.formdefinition')),
            ],
            options={
                'verbose_name': 'Form Submission',
                'ordering': ['-created'],
            },
        ),
        migrations.CreateModel(
            name='FormField',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field_type', models.CharField(choices=[('text', 'Text'), ('email', 'Email'), ('tel', 'Phone'), ('textarea', 'Textarea'), ('number', 'Number'), ('select', 'Dropdown'), ('radio', 'Radio buttons'), ('checkbox', 'Checkbox'), ('hidden', 'Hidden')], default='text', max_length=20)),
                ('name', models.SlugField(help_text='Machine key submitted in the payload, e.g. "phone".', max_length=60)),
                ('label', models.CharField(max_length=120)),
                ('placeholder', models.CharField(blank=True, max_length=150)),
                ('help_text', models.CharField(blank=True, max_length=255)),
                ('required', models.BooleanField(default=False)),
                ('options', models.JSONField(blank=True, default=list, help_text='For dropdown/radio fields — list of option labels.')),
                ('position', models.PositiveIntegerField(default=0)),
                ('form', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fields', to='formbuilder.formdefinition')),
            ],
            options={
                'verbose_name': 'Form Field',
                'ordering': ['position', 'id'],
                'unique_together': {('form', 'name')},
            },
        ),
    ]
