# Generated by Django 5.1.4 on 2026-09-13 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formbuilder', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='formdefinition',
            name='inquiry_type',
            field=models.CharField(blank=True, help_text='Only used when Target is "Leads pipeline" — one of contact / dealer / architect. Leave blank to default to "contact".', max_length=10),
        ),
        migrations.AddField(
            model_name='formdefinition',
            name='target_pipeline',
            field=models.CharField(choices=[('submission', 'Generic submission (view under Forms → Submissions)'), ('inquiry', 'Leads pipeline (view under Leads, same as the Contact form today)')], default='submission', help_text='Where a submission of this form is stored.', max_length=20),
        ),
    ]
