# Generated by Django 5.1.4 on 2026-09-13 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formbuilder', '0003_seed_legacy_forms'),
    ]

    operations = [
        migrations.AddField(
            model_name='formdefinition',
            name='auto_reply_body',
            field=models.TextField(blank=True, default="Hi {{name}},\n\nThanks for reaching out to {{site_name}}. We've received your message and will get back to you shortly.\n\n— {{site_name}} Team", help_text="Supports {{name}}, {{email}}, {{site_name}}, and {{field_name}} for any of this form's own fields."),
        ),
        migrations.AddField(
            model_name='formdefinition',
            name='auto_reply_enabled',
            field=models.BooleanField(default=False, help_text='Send an automatic confirmation email back to the person who submitted this form.'),
        ),
        migrations.AddField(
            model_name='formdefinition',
            name='auto_reply_subject',
            field=models.CharField(blank=True, default='Thanks for contacting {{site_name}}', max_length=200),
        ),
    ]
