# Generated by Django 5.1.4 on 2026-09-13 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formbuilder', '0004_formdefinition_auto_reply_body_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='formdefinition',
            name='webhook_enabled',
            field=models.BooleanField(default=False, help_text='POST every submission as JSON to an external URL — for CRMs, Zapier, Google Sheets, etc.'),
        ),
        migrations.AddField(
            model_name='formdefinition',
            name='webhook_secret',
            field=models.CharField(blank=True, help_text='Optional. Sent as the X-Webhook-Secret header so the receiving end can verify the request came from us.', max_length=200),
        ),
        migrations.AddField(
            model_name='formdefinition',
            name='webhook_url',
            field=models.URLField(blank=True, help_text="e.g. a Zapier/Make catch hook, or your CRM's inbound webhook endpoint.", max_length=500),
        ),
    ]
