# Generated by Django 5.1.4 on 2026-06-04 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='mega_description',
            field=models.CharField(blank=True, help_text='Short description shown under the category name in the mega menu', max_length=120),
        ),
        migrations.AddField(
            model_name='category',
            name='mega_group',
            field=models.CharField(choices=[('none', 'Not in mega menu'), ('finishes', 'Surface Finishes column'), ('panels', 'Panels & Décor column')], default='none', help_text='Which column in the header mega menu this category appears in', max_length=10),
        ),
        migrations.AddField(
            model_name='category',
            name='mega_icon',
            field=models.CharField(blank=True, default='◈', help_text='Single Unicode/emoji character shown in the mega menu', max_length=10),
        ),
        migrations.AddField(
            model_name='category',
            name='mega_position',
            field=models.PositiveSmallIntegerField(default=0, help_text='Order within the mega menu column (lower = first)'),
        ),
        migrations.AddField(
            model_name='collection',
            name='mega_accent_color',
            field=models.CharField(blank=True, default='#7B9EC4', help_text='Hex colour for the accent dot in the mega menu (e.g. #7B9EC4)', max_length=7),
        ),
        migrations.AddField(
            model_name='collection',
            name='mega_position',
            field=models.PositiveSmallIntegerField(default=0, help_text='Order in the mega menu grid (lower = first)'),
        ),
        migrations.AddField(
            model_name='collection',
            name='show_in_mega_menu',
            field=models.BooleanField(default=False, help_text='Show this collection in the header mega menu collections grid'),
        ),
    ]
