# Generated by Django 5.1.4 on 2026-06-05 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_mega_menu_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='short_description',
            field=models.CharField(blank=True, help_text='One-line summary shown on product cards and quick-view modal (max 300 chars)', max_length=300),
        ),
    ]
