# Generated by Django 5.1.4 on 2026-09-08 04:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_short_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='hero_eyebrow',
            field=models.CharField(blank=True, help_text='Small label above the title on the category listing page (e.g. "Surface Collection")', max_length=120),
        ),
        migrations.AddField(
            model_name='category',
            name='hero_image_url',
            field=models.CharField(blank=True, help_text='Hero background image URL. Overrides the banner image when set.', max_length=500),
        ),
        migrations.AddField(
            model_name='product',
            name='accent_color',
            field=models.CharField(blank=True, default='#85addc', help_text="Hex accent colour for this product's card", max_length=7),
        ),
        migrations.AddField(
            model_name='product',
            name='application',
            field=models.CharField(blank=True, help_text='Comma-separated uses, e.g. "Cabinets, Wardrobes, Wall Panels"', max_length=200),
        ),
        migrations.AddField(
            model_name='product',
            name='badge',
            field=models.CharField(blank=True, choices=[('', 'None'), ('New', 'New'), ('Bestseller', 'Bestseller'), ('Limited', 'Limited')], max_length=12),
        ),
        migrations.AddField(
            model_name='product',
            name='color',
            field=models.CharField(blank=True, choices=[('White', 'White'), ('Beige', 'Beige'), ('Black', 'Black'), ('Blue', 'Blue'), ('Brown', 'Brown'), ('Green', 'Green'), ('Grey', 'Grey'), ('Metallic', 'Metallic'), ('Multicolor', 'Multicolor'), ('Orange', 'Orange'), ('Pink', 'Pink'), ('Purple', 'Purple'), ('Red', 'Red'), ('Yellow', 'Yellow')], max_length=20),
        ),
        migrations.AddField(
            model_name='product',
            name='design_type',
            field=models.CharField(blank=True, choices=[('Wood', 'Wood'), ('Stone', 'Stone'), ('Fabric', 'Fabric'), ('Solid', 'Solid'), ('Metallic', 'Metallic')], max_length=20),
        ),
        migrations.AddField(
            model_name='product',
            name='dimensions',
            field=models.CharField(blank=True, help_text='e.g. "8ft × 4ft (2440 × 1220mm)"', max_length=80),
        ),
        migrations.AddField(
            model_name='product',
            name='finish',
            field=models.CharField(blank=True, help_text='e.g. "High Gloss", "Ultra Matte", "Suede"', max_length=60),
        ),
        migrations.AddField(
            model_name='product',
            name='image_urls',
            field=models.JSONField(blank=True, default=list, help_text='External image URLs — used when no Media Library images are attached.'),
        ),
        migrations.AddField(
            model_name='product',
            name='surface',
            field=models.CharField(blank=True, help_text='e.g. "Decorative Laminate"', max_length=80),
        ),
        migrations.AddField(
            model_name='product',
            name='thickness',
            field=models.CharField(blank=True, help_text='e.g. "1.0mm"', max_length=40),
        ),
    ]
