# Generated by Django 5.1.4 on 2026-09-13 18:35

from django.db import migrations, models


def _product_type(collection_name, surface, finish):
    if collection_name == "Fluted":
        return "Decorative Panel"
    if "PVC" in (surface or ""):
        return "PVC Panel"
    if collection_name == "S'Shades":
        return "Premium Laminate (1mm)"
    if finish == "High Gloss":
        return "High Gloss Laminate"
    if "Metallic" in (surface or ""):
        return "Metallic Laminate"
    if finish in ("Matte", "Ultra Matte", "Satin", "Suede"):
        return "Solid Colour Laminate"
    return "Decorative Laminate Sheet"


def _surface_category(collection_name, finish):
    if collection_name == "Fluted":
        return "Architectural Panel"
    if finish == "High Gloss":
        return "Glossy Surface"
    if finish in ("Ultra Matte", "Matte"):
        return "Matt Surface"
    if finish in ("Suede", "Satin"):
        return "Suede Surface"
    if finish == "Textured":
        return "Textured Surface"
    if finish == "Metallic":
        return "Metallic Surface"
    return "Decorative Surface"


def backfill_product_type_and_surface_category(apps, schema_editor):
    """Reproduce the values the storefront used to compute on the fly (see the
    old getProductType/getSurfaceCategory in the Next.js product detail page)
    so existing product pages don't go blank now that these are real fields."""
    Product = apps.get_model("catalog", "Product")
    for p in Product.objects.select_related("collection").all():
        collection_name = p.collection.name if p.collection_id else ""
        p.product_type = _product_type(collection_name, p.surface, p.finish)
        p.surface_category = _surface_category(collection_name, p.finish)
        p.save(update_fields=["product_type", "surface_category"])


def noop_reverse(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0005_seed_catalog'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='product_type',
            field=models.CharField(blank=True, help_text='Shown as a tag and in the specs table, e.g. "Premium Laminate (1mm)", "PVC Panel", "Decorative Panel"', max_length=80),
        ),
        migrations.AddField(
            model_name='product',
            name='surface_category',
            field=models.CharField(blank=True, help_text='Shown as a tag and in the specs table, e.g. "Glossy Surface", "Matt Surface", "Architectural Panel"', max_length=80),
        ),
        migrations.RunPython(backfill_product_type_and_surface_category, noop_reverse),
    ]
