# Generated by Django 5.1.4 on 2026-09-13 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0006_product_product_type_product_surface_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='show_application',
            field=models.BooleanField(default=True, help_text='Show the “Applications” row'),
        ),
        migrations.AddField(
            model_name='product',
            name='show_design_type',
            field=models.BooleanField(default=True, help_text='Show the “Design” tag'),
        ),
        migrations.AddField(
            model_name='product',
            name='show_dimensions',
            field=models.BooleanField(default=True, help_text='Show the “Standard Size” row'),
        ),
        migrations.AddField(
            model_name='product',
            name='show_finish',
            field=models.BooleanField(default=True, help_text='Show the “Finish / Texture” row'),
        ),
        migrations.AddField(
            model_name='product',
            name='show_product_type',
            field=models.BooleanField(default=True, help_text='Show the “Product Type” tag & row'),
        ),
        migrations.AddField(
            model_name='product',
            name='show_surface',
            field=models.BooleanField(default=True, help_text='Show the “Design / Surface” row'),
        ),
        migrations.AddField(
            model_name='product',
            name='show_surface_category',
            field=models.BooleanField(default=True, help_text='Show the “Surface Category” tag & row'),
        ),
        migrations.AddField(
            model_name='product',
            name='show_thickness',
            field=models.BooleanField(default=True, help_text='Show the “Thickness” row'),
        ),
    ]
