# Generated by Django 5.1.4 on 2026-09-15 05:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0008_product_attribute_option'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='application_image_url',
            field=models.CharField(blank=True, help_text="External 'applied in a room' image URL — used when no Media Library application image is attached. Shown below the title on the product page.", max_length=500),
        ),
        migrations.AddField(
            model_name='product',
            name='texture_variants',
            field=models.JSONField(blank=True, default=list, help_text='External texture-variant thumbnails — [{"label": "Fluted", "image_url": "https://…"}, …]. Used when no Media Library texture images are attached.'),
        ),
        migrations.AddField(
            model_name='productimage',
            name='label',
            field=models.CharField(blank=True, help_text='Texture name shown under the thumbnail, e.g. "Fluted", "Glossy" — only used for the Texture role.', max_length=60),
        ),
        migrations.AddField(
            model_name='productimage',
            name='role',
            field=models.CharField(choices=[('gallery', 'Gallery'), ('application', 'Application'), ('texture', 'Texture')], default='gallery', help_text='Where this image is shown on the product page: the main swatch/gallery, the single applied-in-a-room shot below the title, or a texture-variant thumbnail.', max_length=12),
        ),
    ]
