# Generated by Django 5.1.4 on 2026-09-13 19:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(help_text='Referenced by the frontend, e.g. "footer-resources".', max_length=60, unique=True)),
                ('name', models.CharField(max_length=120)),
                ('description', models.CharField(blank=True, max_length=255)),
                ('is_system', models.BooleanField(default=False, help_text='System menus cannot be deleted from the CMS.')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='MenuItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=80)),
                ('url', models.CharField(blank=True, help_text='Relative (/about-us) or absolute URL. Leave blank for a label-only dropdown trigger.', max_length=300)),
                ('open_new_tab', models.BooleanField(default=False)),
                ('position', models.PositiveSmallIntegerField(default=0, help_text='Lower = appears first among its siblings.')),
                ('menu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='menus.menu')),
                ('parent', models.ForeignKey(blank=True, help_text='Leave blank for a top-level item; set to nest as a dropdown submenu item.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='menus.menuitem')),
            ],
            options={
                'ordering': ['position', 'id'],
            },
        ),
    ]
