# Generated by Django 5.1.4 on 2026-09-14 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menus', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='menuitem',
            name='active',
            field=models.BooleanField(default=True, help_text='Inactive items are hidden from the live site without deleting them.'),
        ),
    ]
