# Generated by Django 5.1.4 on 2026-05-30 02:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GlobalSEO',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_meta_title', models.CharField(blank=True, max_length=255)),
                ('site_meta_description', models.TextField(blank=True, max_length=320)),
                ('site_keywords', models.CharField(blank=True, max_length=500)),
                ('robots_txt', models.TextField(blank=True, default='User-agent: *\nAllow: /\nSitemap: https://api.sanishlaminate.com/sitemap.xml')),
                ('ga4_code', models.CharField(blank=True, help_text='G-XXXXXXXXXX', max_length=50)),
                ('gtm_code', models.CharField(blank=True, help_text='GTM-XXXXXXX', max_length=50)),
                ('fb_pixel_code', models.CharField(blank=True, max_length=50)),
                ('clarity_code', models.CharField(blank=True, max_length=50)),
            ],
            options={
                'verbose_name': 'Global SEO Settings',
                'verbose_name_plural': 'Global SEO Settings',
            },
        ),
        migrations.CreateModel(
            name='Redirect',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_path', models.CharField(max_length=500, unique=True)),
                ('destination_path', models.CharField(max_length=500)),
                ('type', models.CharField(choices=[('301', '301 Permanent'), ('302', '302 Temporary')], default='301', max_length=3)),
                ('active', models.BooleanField(default=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['source_path'],
            },
        ),
    ]
