# Generated by Django 5.1.4 on 2026-06-04 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seo', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_name', models.CharField(default='Sanish Laminates', max_length=100)),
                ('tagline', models.CharField(blank=True, default='Premium Decorative Surface Solutions', max_length=200)),
                ('logo_dark_url', models.CharField(blank=True, default='/assets/img/logo/black-logo.svg', help_text='Path or URL for dark/black logo (used on light backgrounds)', max_length=500)),
                ('logo_light_url', models.CharField(blank=True, default='/assets/img/logo/footer-black-logo.svg', help_text='Path or URL for light logo (used on dark backgrounds / footer)', max_length=500)),
                ('favicon_url', models.CharField(blank=True, default='/favicon.ico', max_length=500)),
                ('phone_primary', models.CharField(blank=True, default='+91 7027 777 032', max_length=30)),
                ('phone_secondary', models.CharField(blank=True, max_length=30)),
                ('email_primary', models.EmailField(blank=True, default='info@sanishlaminate.com', max_length=254)),
                ('email_secondary', models.EmailField(blank=True, max_length=254)),
                ('address_line1', models.CharField(blank=True, max_length=200)),
                ('address_line2', models.CharField(blank=True, max_length=200)),
                ('city', models.CharField(blank=True, max_length=80)),
                ('state', models.CharField(blank=True, max_length=80)),
                ('pincode', models.CharField(blank=True, max_length=10)),
                ('working_hours', models.CharField(blank=True, default='Mon–Sat: 9 AM – 6 PM', max_length=100)),
                ('map_embed_url', models.TextField(blank=True, help_text='Full Google Maps embed iframe src URL')),
                ('map_lat', models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True)),
                ('map_lng', models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True)),
                ('instagram_url', models.URLField(blank=True)),
                ('facebook_url', models.URLField(blank=True)),
                ('youtube_url', models.URLField(blank=True)),
                ('pinterest_url', models.URLField(blank=True)),
                ('linkedin_url', models.URLField(blank=True)),
                ('twitter_url', models.URLField(blank=True)),
                ('whatsapp_number', models.CharField(blank=True, default='+917027777032', help_text='With country code, no spaces e.g. +917027777032', max_length=20)),
                ('topbar_badge', models.CharField(blank=True, default='Premium Surface Manufacturing', max_length=100)),
                ('header_cta_label', models.CharField(blank=True, default='Download Catalogue', max_length=60)),
                ('header_cta_url', models.CharField(blank=True, default='#', max_length=300)),
                ('footer_description', models.TextField(blank=True, default='Crafting elegant laminate and decorative surface solutions for architects, interior designers, commercial projects, and modern living spaces across India.')),
                ('footer_copyright', models.CharField(blank=True, default='© 2026 SANISH Laminates. All Rights Reserved.', max_length=200)),
                ('footer_newsletter_text', models.CharField(blank=True, default='Subscribe for new collections, design inspiration, and exclusive dealer offers.', max_length=300)),
            ],
            options={
                'verbose_name': 'Site Settings',
                'verbose_name_plural': 'Site Settings',
            },
        ),
    ]
