# Generated by Django 5.1.4 on 2026-06-04 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seo', '0002_site_settings'),
    ]

    operations = [
        migrations.CreateModel(
            name='NavLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=80)),
                ('url', models.CharField(help_text='Relative (/about-us) or absolute URL', max_length=300)),
                ('open_new_tab', models.BooleanField(default=False)),
                ('group', models.CharField(choices=[('main', 'Main Navigation (desktop nav bar)'), ('topbar', 'Top Bar (above the header)'), ('mega_quick', 'Mega Menu — Bottom Quick Links'), ('footer_company', 'Footer — Company column')], default='main', max_length=20)),
                ('position', models.PositiveSmallIntegerField(default=0, help_text='Lower = appears first')),
                ('active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['group', 'position'],
            },
        ),
    ]
