# Generated by Django 5.1.4 on 2026-08-19 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seo', '0003_nav_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='smtp_from_email',
            field=models.EmailField(blank=True, default='no-reply@sanishlaminate.com', max_length=254),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='smtp_host',
            field=models.CharField(blank=True, help_text="e.g. smtp.gmail.com. Leave blank to use the server's env-configured mail settings.", max_length=255),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='smtp_notify_emails',
            field=models.CharField(blank=True, default='info@sanishlaminate.com,karyaweb2025@gmail.com', help_text='Comma-separated — who receives a notification on every new website form/popup submission.', max_length=500),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='smtp_password',
            field=models.CharField(blank=True, help_text='For Gmail, use an App Password — not your normal account password.', max_length=255),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='smtp_port',
            field=models.PositiveIntegerField(default=587),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='smtp_use_tls',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='smtp_username',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
