# Generated by Django 5.1.4 on 2026-09-13 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seo', '0004_sitesettings_smtp_from_email_sitesettings_smtp_host_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='globalseo',
            name='gsc_verification_code',
            field=models.CharField(blank=True, help_text='Google Search Console HTML tag verification content — from the \'content="..."\' value of the meta tag Search Console gives you (HTML tag verification method), not the whole tag.', max_length=100),
        ),
        migrations.AlterField(
            model_name='globalseo',
            name='clarity_code',
            field=models.CharField(blank=True, help_text='Microsoft Clarity project ID, e.g. abcd1234ef', max_length=50),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='footer_copyright',
            field=models.CharField(blank=True, default='© 2026 SANISH Laminate. All Rights Reserved.', max_length=200),
        ),
    ]
