# Generated by Django 5.1.4 on 2026-09-14 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seo', '0005_globalseo_gsc_verification_code_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ThemeSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('primary_color', models.CharField(default='#C9A227', help_text='Main brand color — buttons, links, highlights', max_length=7)),
                ('secondary_color', models.CharField(default='#1F2937', max_length=7)),
                ('accent_color', models.CharField(default='#85ADDC', help_text='Used for badges, tags and secondary highlights', max_length=7)),
                ('heading_color', models.CharField(default='#24262B', max_length=7)),
                ('text_color', models.CharField(default='#686B72', max_length=7)),
                ('link_color', models.CharField(default='#C9A227', max_length=7)),
                ('link_hover_color', models.CharField(default='#A3831E', max_length=7)),
                ('background_color', models.CharField(default='#FAFAFA', max_length=7)),
                ('header_bg_color', models.CharField(default='#FFFFFF', max_length=7)),
                ('footer_bg_color', models.CharField(default='#1A1A2E', max_length=7)),
                ('footer_text_color', models.CharField(default='#F5F5F5', max_length=7)),
                ('heading_font', models.CharField(choices=[('Inter', 'Inter'), ('Roboto', 'Roboto'), ('Poppins', 'Poppins'), ('Montserrat', 'Montserrat'), ('Open Sans', 'Open Sans'), ('Lato', 'Lato'), ('Nunito', 'Nunito'), ('Playfair Display', 'Playfair Display'), ('Raleway', 'Raleway'), ('Work Sans', 'Work Sans'), ('Mulish', 'Mulish'), ('DM Sans', 'DM Sans'), ('Manrope', 'Manrope'), ('Outfit', 'Outfit'), ('Sora', 'Sora'), ('Space Grotesk', 'Space Grotesk')], default='Poppins', max_length=40)),
                ('body_font', models.CharField(choices=[('Inter', 'Inter'), ('Roboto', 'Roboto'), ('Poppins', 'Poppins'), ('Montserrat', 'Montserrat'), ('Open Sans', 'Open Sans'), ('Lato', 'Lato'), ('Nunito', 'Nunito'), ('Playfair Display', 'Playfair Display'), ('Raleway', 'Raleway'), ('Work Sans', 'Work Sans'), ('Mulish', 'Mulish'), ('DM Sans', 'DM Sans'), ('Manrope', 'Manrope'), ('Outfit', 'Outfit'), ('Sora', 'Sora'), ('Space Grotesk', 'Space Grotesk')], default='Inter', max_length=40)),
                ('base_font_size', models.CharField(choices=[('14px', 'Small (14px)'), ('16px', 'Default (16px)'), ('18px', 'Large (18px)')], default='16px', max_length=10)),
                ('button_style', models.CharField(choices=[('solid', 'Solid'), ('outline', 'Outline'), ('ghost', 'Ghost (text only)'), ('soft', 'Soft (tinted)')], default='solid', max_length=10)),
                ('button_radius', models.CharField(choices=[('0px', 'Square'), ('4px', 'Small'), ('8px', 'Medium'), ('12px', 'Large'), ('9999px', 'Pill')], default='8px', max_length=10)),
                ('button_hover_effect', models.CharField(choices=[('darken', 'Darken'), ('lighten', 'Lighten'), ('scale', 'Scale up'), ('none', 'None')], default='darken', max_length=10)),
                ('button_text_color', models.CharField(default='#FFFFFF', help_text='Text color on solid/soft buttons', max_length=7)),
                ('container_max_width', models.CharField(choices=[('1120px', 'Narrow (1120px)'), ('1280px', 'Default (1280px)'), ('1440px', 'Wide (1440px)'), ('1600px', 'Extra Wide (1600px)')], default='1280px', max_length=10)),
                ('border_radius', models.CharField(choices=[('0px', 'None'), ('6px', 'Small'), ('12px', 'Medium'), ('20px', 'Large'), ('28px', 'Extra Large')], default='12px', help_text='Global corner radius for cards, inputs and images', max_length=10)),
                ('card_shadow_style', models.CharField(choices=[('none', 'None'), ('soft', 'Soft'), ('medium', 'Medium'), ('strong', 'Strong')], default='soft', max_length=10)),
            ],
            options={
                'verbose_name': 'Theme Settings',
                'verbose_name_plural': 'Theme Settings',
            },
        ),
    ]
