# Generated by Django 5.1.4 on 2026-09-14 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seo', '0006_themesettings'),
    ]

    operations = [
        migrations.AlterField(
            model_name='themesettings',
            name='accent_color',
            field=models.CharField(default='#FABF7D', help_text='Sanish Apricot — badges, tags and small decorative highlights', max_length=7),
        ),
        migrations.AlterField(
            model_name='themesettings',
            name='base_font_size',
            field=models.CharField(choices=[('14px', 'Small (14px)'), ('15px', 'Default (15px)'), ('16px', 'Large (16px)'), ('18px', 'Extra Large (18px)')], default='15px', max_length=10),
        ),
        migrations.AlterField(
            model_name='themesettings',
            name='body_font',
            field=models.CharField(choices=[('Heebo', 'Heebo — current body/UI font'), ('Bodoni Moda', 'Bodoni Moda — current heading font (fallback for the licensed “Vogue” display face)'), ('Inter', 'Inter'), ('Roboto', 'Roboto'), ('Poppins', 'Poppins'), ('Montserrat', 'Montserrat'), ('Open Sans', 'Open Sans'), ('Lato', 'Lato'), ('Nunito', 'Nunito'), ('Playfair Display', 'Playfair Display'), ('Raleway', 'Raleway'), ('Work Sans', 'Work Sans'), ('Mulish', 'Mulish'), ('DM Sans', 'DM Sans'), ('Manrope', 'Manrope'), ('Outfit', 'Outfit'), ('Sora', 'Sora'), ('Space Grotesk', 'Space Grotesk')], default='Heebo', max_length=40),
        ),
        migrations.AlterField(
            model_name='themesettings',
            name='border_radius',
            field=models.CharField(choices=[('0px', 'None'), ('6px', 'Small'), ('12px', 'Medium'), ('20px', 'Large — current site style'), ('28px', 'Extra Large')], default='20px', help_text='Global corner radius for cards, inputs and images', max_length=10),
        ),
        migrations.AlterField(
            model_name='themesettings',
            name='button_hover_effect',
            field=models.CharField(choices=[('swap', 'Swap to accent color — current site style'), ('darken', 'Darken'), ('lighten', 'Lighten'), ('scale', 'Scale up'), ('none', 'None')], default='swap', max_length=10),
        ),
        migrations.AlterField(
            model_name='themesettings',
            name='button_radius',
            field=models.CharField(choices=[('0px', 'Square'), ('4px', 'Small'), ('8px', 'Medium'), ('12px', 'Large'), ('9999px', 'Pill — current site style')], default='9999px', max_length=10),
        ),
        migrations.AlterField(
            model_name='themesettings',
            name='container_max_width',
            field=models.CharField(choices=[('1120px', 'Narrow (1120px)'), ('1280px', 'Wide (1280px)'), ('1400px', 'Default (1400px) — current site width'), ('1600px', 'Extra Wide (1600px)')], default='1400px', max_length=10),
        ),
        migrations.AlterField(
            model_name='themesettings',
            name='footer_bg_color',
            field=models.CharField(default='#F3F4F6', help_text='Footer uses a soft pink→purple gradient fading into this color in production — this is its flat approximation', max_length=7),
        ),
        migrations.AlterField(
            model_name='themesettings',
            name='footer_text_color',
            field=models.CharField(default='#686B72', max_length=7),
        ),
        migrations.AlterField(
            model_name='themesettings',
            name='header_bg_color',
            field=models.CharField(default='#FFFFFF', help_text='Header is a translucent frosted-glass bar over white in production — this is its flat approximation', max_length=7),
        ),
        migrations.AlterField(
            model_name='themesettings',
            name='heading_font',
            field=models.CharField(choices=[('Heebo', 'Heebo — current body/UI font'), ('Bodoni Moda', 'Bodoni Moda — current heading font (fallback for the licensed “Vogue” display face)'), ('Inter', 'Inter'), ('Roboto', 'Roboto'), ('Poppins', 'Poppins'), ('Montserrat', 'Montserrat'), ('Open Sans', 'Open Sans'), ('Lato', 'Lato'), ('Nunito', 'Nunito'), ('Playfair Display', 'Playfair Display'), ('Raleway', 'Raleway'), ('Work Sans', 'Work Sans'), ('Mulish', 'Mulish'), ('DM Sans', 'DM Sans'), ('Manrope', 'Manrope'), ('Outfit', 'Outfit'), ('Sora', 'Sora'), ('Space Grotesk', 'Space Grotesk')], default='Bodoni Moda', max_length=40),
        ),
        migrations.AlterField(
            model_name='themesettings',
            name='link_color',
            field=models.CharField(default='#AC8CC0', max_length=7),
        ),
        migrations.AlterField(
            model_name='themesettings',
            name='link_hover_color',
            field=models.CharField(default='#F39BA2', help_text='Sanish Pink — hover/focus/active state across the whole site', max_length=7),
        ),
        migrations.AlterField(
            model_name='themesettings',
            name='primary_color',
            field=models.CharField(default='#AC8CC0', help_text='Main brand color — buttons, links, CTAs and the active-nav indicator', max_length=7),
        ),
        migrations.AlterField(
            model_name='themesettings',
            name='secondary_color',
            field=models.CharField(default='#85ADDC', help_text='Sanish Blue — secondary brand color', max_length=7),
        ),
        migrations.AlterField(
            model_name='themesettings',
            name='text_color',
            field=models.CharField(default='#24262B', max_length=7),
        ),
    ]
