# Generated by Django 5.1.4 on 2026-09-15 05:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seo', '0007_alter_themesettings_accent_color_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='globalseo',
            name='recaptcha_secret_key',
            field=models.CharField(blank=True, help_text='reCAPTCHA secret key (server-side only, never exposed to the frontend).', max_length=100),
        ),
        migrations.AddField(
            model_name='globalseo',
            name='recaptcha_site_key',
            field=models.CharField(blank=True, help_text='reCAPTCHA site key (public).', max_length=100),
        ),
        migrations.AddField(
            model_name='globalseo',
            name='recaptcha_v3_min_score',
            field=models.DecimalField(decimal_places=2, default=0.5, help_text='v3 only — submissions scoring below this (0.0-1.0, higher = more human) are rejected as spam.', max_digits=3),
        ),
        migrations.AddField(
            model_name='globalseo',
            name='recaptcha_version',
            field=models.CharField(choices=[('off', 'Off'), ('v2', 'v2 ("I\'m not a robot" checkbox)'), ('v3', 'v3 (invisible, score-based)')], default='off', max_length=3),
        ),
    ]
