# Generated by Django 5.1.4 on 2026-09-24 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seo', '0008_globalseo_recaptcha_secret_key_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sitesettings',
            name='header_cta_url',
            field=models.CharField(blank=True, default='/collection', help_text="Where the header's CTA button links to, e.g. /collection or a full URL", max_length=300),
        ),
    ]
