# Generated by Django 5.1.4 on 2026-09-09 05:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('media_library', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mediafolder',
            options={'ordering': ['name']},
        ),
        migrations.AddField(
            model_name='mediaasset',
            name='caption',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='mediaasset',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='mediaasset',
            name='original_filename',
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AddField(
            model_name='mediaasset',
            name='updated',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name='mediafolder',
            name='created',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
